<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="0" hostname="yaokaideMacBook-Pro.local" failures="0" tests="9" name="com.tester.cases.XHSv1Test" time="21.561" errors="1" timestamp="07 Feb 2020 05:35:51 GMT" skipped="0">
  <testcase classname="com.tester.cases.XHSv1Test" name="user_focus" time="0.508"/>
  <testcase classname="com.tester.cases.XHSv1Test" name="user_info" time="0.488"/>
  <testcase classname="com.tester.cases.XHSv1Test" name="note_comments" time="0.526"/>
  <testcase classname="com.tester.cases.XHSv1Test" name="user_fans" time="1.531"/>
  <testcase classname="com.tester.cases.XHSv1Test" name="user_video" time="0.790"/>
  <testcase classname="com.tester.cases.XHSv1Test" name="video_detail" time="0.869"/>
  <testcase classname="com.tester.cases.XHSv1Test" name="user_note" time="0.307">
    <error message="{&quot;code&quot;: -1, &quot;data&quot;: null, &quot;msg&quot;: &quot;xhs1 参数错误&quot;, &quot;start_time&quot;: 1581053196, &quot;end_time&quot;: 1581053197}
请求url：http://47.97.206.10/api/xhs_v1/user_note?user_id=5a73c5fa4eacab4c4ccc9778&amp;page=1&amp;page_size=10" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: {"code": -1, "data": null, "msg": "xhs1 参数错误", "start_time": 1581053196, "end_time": 1581053197}
请求url：http://47.97.206.10/api/xhs_v1/user_note?user_id=5a73c5fa4eacab4c4ccc9778&page=1&page_size=10
	at com.tester.cases.XHSv1Test.user_note(XHSv1Test.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </error>
  </testcase> <!-- user_note -->
  <testcase classname="com.tester.cases.XHSv1Test" name="note_detail" time="0.724"/>
  <testcase classname="com.tester.cases.XHSv1Test" name="home_feed" time="15.818"/>
</testsuite> <!-- com.tester.cases.XHSv1Test -->
